
  create table "public"."places" (
    "id" bigint generated by default as identity not null,
    "country" text not null,
    "city" text not null,
    "lat" double precision,
    "lng" double precision
      );


alter table "public"."places" enable row level security;


  create table "public"."user_destinations" (
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "destination_country" text,
    "destination_city" text,
    "id" uuid not null default gen_random_uuid()
      );


alter table "public"."user_destinations" enable row level security;

alter table "public"."users" add column "destination_city" text;

CREATE UNIQUE INDEX places_city_key ON public.places USING btree (city);

CREATE UNIQUE INDEX places_pkey ON public.places USING btree (id);

CREATE UNIQUE INDEX user_destinations_pkey ON public.user_destinations USING btree (id);

alter table "public"."places" add constraint "places_pkey" PRIMARY KEY using index "places_pkey";

alter table "public"."user_destinations" add constraint "user_destinations_pkey" PRIMARY KEY using index "user_destinations_pkey";

alter table "public"."places" add constraint "lat_range" CHECK (((lat >= ('-90'::integer)::double precision) AND (lat <= (90)::double precision))) not valid;

alter table "public"."places" validate constraint "lat_range";

alter table "public"."places" add constraint "lng_range" CHECK (((lng >= ('-180'::integer)::double precision) AND (lng <= (180)::double precision))) not valid;

alter table "public"."places" validate constraint "lng_range";

alter table "public"."places" add constraint "places_city_key" UNIQUE using index "places_city_key";

alter table "public"."user_destinations" add constraint "fk_user" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_destinations" validate constraint "fk_user";

alter table "public"."user_destinations" add constraint "user_destinations_destination_city_fkey" FOREIGN KEY (destination_city) REFERENCES public.places(city) not valid;

alter table "public"."user_destinations" validate constraint "user_destinations_destination_city_fkey";

grant delete on table "public"."places" to "anon";

grant insert on table "public"."places" to "anon";

grant references on table "public"."places" to "anon";

grant select on table "public"."places" to "anon";

grant trigger on table "public"."places" to "anon";

grant truncate on table "public"."places" to "anon";

grant update on table "public"."places" to "anon";

grant delete on table "public"."places" to "authenticated";

grant insert on table "public"."places" to "authenticated";

grant references on table "public"."places" to "authenticated";

grant select on table "public"."places" to "authenticated";

grant trigger on table "public"."places" to "authenticated";

grant truncate on table "public"."places" to "authenticated";

grant update on table "public"."places" to "authenticated";

grant delete on table "public"."places" to "service_role";

grant insert on table "public"."places" to "service_role";

grant references on table "public"."places" to "service_role";

grant select on table "public"."places" to "service_role";

grant trigger on table "public"."places" to "service_role";

grant truncate on table "public"."places" to "service_role";

grant update on table "public"."places" to "service_role";

grant delete on table "public"."user_destinations" to "anon";

grant insert on table "public"."user_destinations" to "anon";

grant references on table "public"."user_destinations" to "anon";

grant select on table "public"."user_destinations" to "anon";

grant trigger on table "public"."user_destinations" to "anon";

grant truncate on table "public"."user_destinations" to "anon";

grant update on table "public"."user_destinations" to "anon";

grant delete on table "public"."user_destinations" to "authenticated";

grant insert on table "public"."user_destinations" to "authenticated";

grant references on table "public"."user_destinations" to "authenticated";

grant select on table "public"."user_destinations" to "authenticated";

grant trigger on table "public"."user_destinations" to "authenticated";

grant truncate on table "public"."user_destinations" to "authenticated";

grant update on table "public"."user_destinations" to "authenticated";

grant delete on table "public"."user_destinations" to "service_role";

grant insert on table "public"."user_destinations" to "service_role";

grant references on table "public"."user_destinations" to "service_role";

grant select on table "public"."user_destinations" to "service_role";

grant trigger on table "public"."user_destinations" to "service_role";

grant truncate on table "public"."user_destinations" to "service_role";

grant update on table "public"."user_destinations" to "service_role";


  create policy "Enable read access for all users"
  on "public"."places"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."user_destinations"
  as permissive
  for insert
  to authenticated
with check (true);



